name: f1.telemetry

services:
  f1.telemetry.web:
    image: f1.telemetry.web
    build:
      context: .
      dockerfile: F1.Telemetry.Web/Dockerfile

  f1.telemetry.collector:
    image: f1.telemetry.collector
    build:
      context: .
      dockerfile: F1.Telemetry.Collector/Dockerfile
      
  database:
    image: mongodb/mongodb-community-server:8.0-ubi9
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: f1user
      MONGO_INITDB_ROOT_PASSWORD: f1pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db