name: f1.telemetry

services:
  f1.telemetry.web:
    image: f1.telemetry.web
    build:
      context: .
      dockerfile: Backend/F1.Telemetry.Web/Dockerfile

  f1.telemetry.collector:
    image: f1.telemetry.collector
    build:
      context: .
      dockerfile: Backend/F1.Telemetry.Collector/Dockerfile
      
  database:
    image: mongodb/mongodb-community-server:8.0-ubuntu2204
    ports:
      - 27017:27017
    environment:
      MONGODB_INITDB_ROOT_USERNAME: f1user
      MONGODB_INITDB_ROOT_PASSWORD : f1pass
    volumes:
      - ./data:/data/db